name: gem_scramble
description: A competitive word scramble game with virtual gem economy
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0

  # Game engine
  flame: ^1.32.0
  flame_forge2d: ^0.19.2

  # State management
  provider: ^6.1.5+1

  # HTTP and networking
  http: ^1.5.0

  # UI and animations
  cupertino_icons: ^1.0.2
  google_fonts: ^6.3.2
  lottie: ^3.3.2

  # Utilities
  shared_preferences: ^2.5.3
  uuid: ^4.5.1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - lib/animations/
